#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_mail=$(ynh_user_get_info --username="$admin" --key=mail)

secret=$(ynh_string_random 24) # A bug don't allow to do random string bigger than 24
ynh_app_setting_set --app="$app" --key=secret --value="$secret"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/sources"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..."

if [ "$path" = "/" ]; then
    cdgpath=""
else
    cdgpath="${path:1}/"
fi

ynh_add_config --template="settings_local.py.example" --destination="$install_dir/sources/compteur/settings_local.py"
ynh_add_config --template="gunicorn_config.py" --destination="$install_dir/sources/gunicorn_config.py"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression --message="Building app..."

_venv_install

pushd "$install_dir/sources"
    ynh_exec_as "$app" "$venvpy" -m pip install gunicorn
    ynh_exec_as "$app" "$venvpy" -m pip install -r "requirements.txt" -r "requirements-yunohost.txt"

    ynh_exec_as "$app" "$venvpy" manage.py migrate --noinput
    ynh_exec_as "$app" "$venvpy" manage.py collectstatic --noinput

    echo "UPDATE base_localsettings SET mail_from = 'Le compteur du GASE <le-compteur@$domain>';" |  ynh_exec_as "$app" "$venvpy" manage.py dbshell
    ynh_exec_as "$app" "$venvpy" manage.py loaddata initial_database.json
popd

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated systemd config
ynh_add_systemd_config
yunohost service add "$app" --log "/var/log/$app/error.log" "/var/log/$app/access.log"

# Use logrotate to manage application logfile(s)
ynh_use_logrotate
chown -R "$app:www-data" "/var/log/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..."

# Start a systemd service
ynh_systemd_action --service_name="$app" --action="start" --log_path="systemd" --line_match="Started"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed"
