#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_mail=$(ynh_user_get_info --username="$admin" --key=mail)

secret=$(ynh_string_random --length=24) # A bug don't allow to do random string bigger than 24
ynh_app_setting_set --key=secret --value="$secret"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/sources"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

if [ "$path" = "/" ]; then
    cdgpath=""
else
    cdgpath="${path:1}/"
fi

ynh_config_add --template="settings_local.py.example" --destination="$install_dir/sources/compteur/settings_local.py"
ynh_config_add --template="gunicorn_config.py" --destination="$install_dir/sources/gunicorn_config.py"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

_venv_install

pushd "$install_dir/sources"
    ynh_exec_as_app "$venvpy" -m pip install gunicorn
    ynh_exec_as_app "$venvpy" -m pip install -r "requirements.txt" -r "requirements-yunohost.txt"

    ynh_exec_as_app "$venvpy" manage.py migrate --noinput
    ynh_exec_as_app "$venvpy" manage.py collectstatic --noinput

    echo "UPDATE base_localsettings SET mail_from = 'Le compteur du GASE <le-compteur@$domain>';" | ynh_exec_as_app "$venvpy" manage.py dbshell
    ynh_exec_as_app "$venvpy" manage.py loaddata initial_database.json
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --log "/var/log/$app/error.log" "/var/log/$app/access.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
