#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_mail=$(ynh_user_get_info --username="$admin" --key=mail)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# MIGRATION : Enable django auth module
if ! grep -q 'YNH_INTEGRATION_ENABLED = True' "$install_dir/sources/compteur/settings_local.py"; then
    echo 'YNH_INTEGRATION_ENABLED = True' >> "$install_dir/sources/compteur/settings_local.py"
fi

# Move sources to subdir
if [ ! -d "$install_dir/sources" ]; then
    mkdir "$install_dir/sources"
    find . -mindepth 1 -maxdepth 1 ! -name "sources" -exec mv -t "$install_dir/sources" "{}" +
fi

# Move database out of sources dir (avoid to overwrite it on upgrade…)
if [ -f $install_dir/sources/db.sqlite3 ]; then
    mv $install_dir/sources/db.sqlite3 $data_dir/db.sqlite3
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/sources" --full_replace

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

if [ "$path" = "/" ]; then
    cdgpath=""
else
    cdgpath="${path:1}/"
fi

ynh_config_add --template="settings_local.py.example" --destination="$install_dir/sources/compteur/settings_local.py"
ynh_config_add --template="gunicorn_config.py" --destination="$install_dir/sources/gunicorn_config.py"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

_venv_install

pushd "$install_dir/sources"
    ynh_exec_as_app "$venvpy" -m pip install gunicorn
    ynh_exec_as_app "$venvpy" -m pip install -r requirements.txt -r requirements-yunohost.txt
    ynh_exec_as_app "$venvpy" manage.py migrate --noinput
popd

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --log "/var/log/$app/error.log" "/var/log/$app/access.log"

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
