#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_mail=$(ynh_user_get_info --username="$admin" --key=mail)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping $app's systemd service..."

ynh_systemd_action --service_name="$app" --action="stop" --log_path="systemd"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..."

# MIGRATION : migrate from setting-based permission to new-style permissions
if [ -n "${is_home_public:-}" ]; then
    if [[ $is_home_public -eq 1 ]]; then
        ynh_permission""_update --permission main --add visitors
    else
        ynh_permission""_update --permission main --remove visitors
    fi
    ynh_app_setting_delete --app="$app" --key=is_home_public
fi

# MIGRATION : Enable django auth module
if ! grep -q 'YNH_INTEGRATION_ENABLED = True' "$install_dir/sources/compteur/settings_local.py"; then
    echo 'YNH_INTEGRATION_ENABLED = True' >> "$install_dir/sources/compteur/settings_local.py"
fi

# Move sources to subdir
if [ ! -d "$install_dir/sources" ]; then
    mkdir "$install_dir/sources"
    find . -mindepth 1 -maxdepth 1 ! -name "sources" -exec mv -t "$install_dir/sources" "{}" +
fi

# Move database out of sources dir (avoid to overwrite it on upgrade…)
if [ -f $install_dir/sources/db.sqlite3 ]; then
    cp $install_dir/sources/db.sqlite3 $install_dir/db.sqlite3
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/sources" --full_replace=1

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..."

if [ "$path" = "/" ]; then
    cdgpath=""
else
    cdgpath="${path:1}/"
fi

ynh_add_config --template="settings_local.py.example" --destination="$install_dir/sources/compteur/settings_local.py"
ynh_add_config --template="gunicorn_config.py" --destination="$install_dir/sources/gunicorn_config.py"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression --message="Building app..."

_venv_install

pushd "$install_dir/sources"
    ynh_exec_as "$app" "$venvpy" -m pip install gunicorn
    ynh_exec_as "$app" "$venvpy" -m pip install -r requirements.txt -r requirements-yunohost.txt

    ynh_exec_as "$app" "$venvpy" manage.py migrate --noinput
popd

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

ynh_add_systemd_config
yunohost service add "$app" --log "/var/log/$app/error.log" "/var/log/$app/access.log"

# Use logrotate to manage app-specific logfile(s)
ynh_use_logrotate --non-append
chown -R "$app:www-data" "/var/log/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..."

ynh_systemd_action --service_name="$app" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed"
